name: open_earable_flutter_edge_ml_connection
description: Connects OpenEarables and other wearables to Edge-ML
version: 0.0.1
repository: https://github.com/OpenEarable/open_earable_flutter_edge_ml_connection

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  open_earable_flutter:
    git:
      url: https://github.com/OpenEarable/open_earable_flutter.git
      ref: main
  edge_ml_dart: ^0.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
