name: open_earable_flutter_edge_ml_connection
description: Connects OpenEarables and other wearables to Edge-ML
version: 0.0.2
repository: https://github.com/OpenEarable/open_earable_flutter_edge_ml_connection

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  open_earable_flutter: ^0.1.0
  edge_ml_dart: ^0.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
